language: ruby
rvm:
- 2.2.0
addons:
  ssh_known_hosts: fireplug.dreamhost.com
before_script:
 - chmod +x ./script/cibuild
 - chmod +x ./script/cideploy
 - sudo apt-get install -qq sshpass

script: 

branches:
  only:
  - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: true # route your build to the container-based infrastructure for a faster build

after_success: ./script/cideploy
