language: ruby
rvm:
- 2.2.5
addons:
  ssh_known_hosts: fireplug.dreamhost.com
before_script:
 - chmod +x ./script/cibuild
 - chmod +x ./script/cideploy
 - sudo apt-get install -qq sshpass

script: ./script/cibuild

branches:
  only:
  - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

dist: trusty
sudo: required

after_success: ./script/cideploy
