language: ruby
rvm:
- 2.2.0
addons:
  ssh_known_hosts: fireplug.dreamhost.com
  code_climate:
    repo_token: e28174b01321fbf580df95b2b0b72644273a1acc65be77318ee2869daecec1e6
before_script:
  - chmod +x ./script/imageprep
  - chmod +x ./script/cibuild
  - chmod +x ./script/cideploy
script:
  - ./script/imageprep
  - ./script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
after_success: "./script/cideploy"
before_install:
- openssl aes-256-cbc -K $encrypted_c56f808d3935_key -iv $encrypted_c56f808d3935_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
