title: Matthew Graybosch
name: Matthew Graybosch
author: Matthew Graybosch
email: /contact/
real_email: matthew@matthewgraybosch.com
locale: en_US
location: "Harrisburg, PA"
description: > # this means to ignore newlines until "baseurl:"
  Hi. I'm Matthew Graybosch, author of the Starbreaker science fantasy novels, developer, and metalhead from New York currently living in Pennsylvania. This is my website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.matthewgraybosch.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: metalheadscifi
github_username:  matthewgraybosch

# Jekyll SEO Tag settings.
twitter:
  username: metalheadscifi

social:
  name: Matthew Graybosch
  links:
    - https://plus.google.com/+MatthewGraybosch
    - https://plus.google.com/u/0/101103204333421326989
    - https://twitter.com/MGraybosch
    - https://twitter.com/metalheadscifi
    - https://facebook.com/matthew.graybosch
    - https://facebook.com/matthewgrayboschnovelist
    - https://www.linkedin.com/in/matthew-graybosch-956331125
    - https://github.com/matthewgraybosch
    - https://www.reddit.com/user/asuraemulator/
    - https://ello.co/starbreaker
    - https://psnprofiles.com/EddieVanHelsing

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/fullsize/author-nyc.jpg

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - .travis.yml
  - CNAME
  - Gemfile.lock
  - package.json
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - ./script
  - ./docs # ignore Minimal Mistakes /docs
  - ./test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: none
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    disable: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York


# Plugins
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
