#!/usr/bin/env bash
set -e # halt script on error

./imageprep

# Let's build the site.
if [[ "$IS_TRAVIS" ]]
  then bundle exec jekyll build --config _config.yml
  else bundle exec jekyll build --config _config.yml _config.dev.yml
fi

# Make target directories for images.
mkdir -p _site/assets/images/fullsize/
mkdir -p _site/assets/images/resized/

# Gotta copy over images.
rsync -avzh _assets/images/fullsize/ _site/assets/images/fullsize/
rsync -avzh _assets/images/resized/ _site/assets/images/resized/

# Now let's check the pages.
bundle exec htmlproofer ./_site --allow-hash-href --disable-external