#!/usr/bin/env bash
set -e # halt script on error

# NEVER RUN THIS AS PART OF THE BUILD PROCESS! IT TAKES TOO FUCKING LONG!

# We need to resize and compress images for display. 
# Script based on "Efficient Image Resizing With ImageMagick" by Dave Newton
# https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/
echo "Image Processing: START..."

export INPUT_PATH=_assets/images/fullsize/
export OUTPUT_WIDTH=700
export OUTPUT_PATH=_assets/images/resized/

rsync -avzh _assets/images/fullsize/ _assets/images/resized/
jpegoptim --size=150k --all-progressive --strip-all ./_assets/images/resized/*.jpg

echo "Image Processing: END..."