#!/usr/bin/env bash
set -e # halt script on error

# NEVER RUN THIS AS PART OF THE BUILD PROCESS! IT TAKES TOO FUCKING LONG!

# We need to resize and compress images for display. 
# Script based on "Efficient Image Resizing With ImageMagick" by Dave Newton
# https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/
echo "Image Processing: START..."

export INPUT_PATH=_assets/images/fullsize/
export OUTPUT_WIDTH=700
export OUTPUT_PATH=_assets/images/resized/

rsync -avzh $INPUT_PATH $OUTPUT_PATH

for img in ${OUTPUT_PATH}*
do
  convert $img -resize 700 $img 
  jpegoptim --size=75k --all-progressive --strip-all $img
done

echo "Image Processing: END..."